### ISSUE TITLE
meo wifi changed again...

### ISSUE THREAD

**Issue by tiagonunesandre** [ravemir/meo-wifi-login#12]
Hi @ravemir 

Just tried your script without success. I noticed they changed the link again.
The original page now returns "Conteúdo indisponível de momento."

I noticed now that the login calls something like:
https://servicoswifi.apps.meo.pt/HotspotConnection.svc/Login?callback=jQuery00000000000_00000000&username=USER@MAIL.PT&password=XXXXXXXX==&navigatorLang=en&_=0000000000

.svc instead of .asmx and also this jQuery callback.

Still trying to figure out if those numbers have any sequence or meaning.

Cheers

**Comment by joaormatos** [comment]
@tiagonunesandre Thank you for the bug report, it turned out to be an easy fix and I already created a pull request.

As for the `callback` parameter, it was already there before and it's inconsequential to us.
They're using an obsolete AJAX technique called [JSONP](https://en.wikipedia.org/wiki/JSONP) and that parameter is just telling the server what the name of the JSONP wrapping function call should be.
