### ISSUE TITLE
meo wifi changed!

### ISSUE THREAD

**Issue by anmaped** [ravemir/meo-wifi-login#3]
Now only the GET method is supported (jsonp) and the url is also different.

curl --insecure "https://servicoswifi.apps.meo.pt/HotspotConnection.asmx/Login?username=XXX@sapo.pt&password=XXX&navigatorLang=pt&callback=foo"

**Comment by ravemir** [comment]
Hey! Thanks for reaching out and letting me know about the change!

Can you let know if I can still test this by checking out the network requests with Chrome's Dev Tools, while connected to a MEO-Wifi hotspot?

**Comment by anmaped** [comment]
@ravemir  I guess yes.

**Comment by ravemir** [comment]
Done and merged to master. Could you please test and give me your feedback, @anmaped ?

**Comment by danielmotaleite** [comment]
new version is working, after i have done the git pull to update my script

So this can be closed.

Thanks for the script! :)

**Comment by anmaped** [comment]
Yes. It's working. @danielmotaleite  thanks for testing it.

**Comment by anmaped** [comment]
@ravemir I have also a login script for fon-zon. Do you want to merge it ?

**Comment by ravemir** [comment]
Hey, there @anmaped! Sorry for looooooong delay 😅 !

Wouldn't say no to that, only see two minor issues:
1.  I could find an hotspot to test it, but no credentials (maybe I can lift one from unsuspecting family members ? 🤔)
2. The OCD in me is having trouble letting go of the fact that the repo is called "meo-wifi" and we'd merge unrelated functionality into it.

Having said that, I think it's worth it, so if you haven't changed your mind, let her rip!
(closing this since it's been fixed for almost 2 years now)
